name: Check links
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "17 7 * * *"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --verbose --no-progress --exclude-mail --exclude-url "linkedin.com" --exclude-url "amazon.com" --timeout 20 --exclude-path ./node_modules --exclude-path ./.git .
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
